version: '3'

services:
  # db:
  #   image: mongo:latest
  #   container_name: app
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./data/db:/data/db
  #   ports: 
  #     - 27017:27017
  #   command: mongod --logpath=/dev/null

  app:
    image: bachelorarbeit
    container_name: bachelorarbeit_app
    ports:
      - 80:8080
      # - 8080:8080
      # - 8000:8000
      # - 14694:8080
      # - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - server/.env
    volumes:
      - .:/app
    # depends_on:
    #   - db
